-- MySQL Script generated by MySQL Workbench
-- Wed Feb 27 13:27:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema antons_skafferi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema antons_skafferi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `antons_skafferi` DEFAULT CHARACTER SET utf8 ;
USE `antons_skafferi` ;

-- -----------------------------------------------------
-- Table `antons_skafferi`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`bookings` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `table_id` INT NOT NULL,
  `people` INT NOT NULL,
  `date` DATE NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `state` TINYINT NOT NULL,
  `time_period_id` INT NOT NULL,
  PRIMARY KEY (`booking_id`),
  INDEX `fk_tables_booking_idx` (`table_id` ASC) ,
  INDEX `fk_time_period_bookings_idx` (`time_period_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`employees` (
  `employees_id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `ssn` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`employees_id`),
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`event_id`),
  INDEX `fk_images_events_idx` (`image_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`groups` (
  `group_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `srs` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `ingredients` VARCHAR(255) NULL,
  `category` INT NOT NULL,
  `prize` INT NULL,
  `images_id` INT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_images_items_idx` (`images_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`logins` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `group_id` INT NULL,
  `employees_id` INT NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_employees_login_idx` (`employees_id` ASC),
  INDEX `fk_groups_logins_idx` (`group_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`orderd_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`orderd_items` (
  `orded_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NULL,
  `item_id` INT NULL,
  `done` TINYINT NULL,
  `employees_id` INT NULL,
  PRIMARY KEY (`orded_item_id`),
  INDEX `fk_orders_order_items_idx` (`order_id` ASC),
  INDEX `fk_items_order_items_idx` (`item_id` ASC),
  INDEX `fk_employees_orderd_items_idx` (`employees_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT NULL,
  `table_id` INT NULL,
  `booking_id` INT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_bookings_orders_idx` (`booking_id` ASC),
  INDEX `fk_tables_orders_idx` (`table_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`schedules` (
  `date` DATE NOT NULL,
  `employees_id` INT NOT NULL,
  `start_hour` TIME NOT NULL,
  `end_hour` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`date`, `employees_id`, `start_hour`),
  INDEX `fk_employees_schedules_idx` (`employees_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`tables` (
  `table_id` INT NOT NULL AUTO_INCREMENT,
  `seat` SMALLINT NOT NULL,
  PRIMARY KEY (`table_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`time_periods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`time_periods` (
  `time_period_id` INT NOT NULL AUTO_INCREMENT,
  `time_period` TIME NULL,
  PRIMARY KEY (`time_period_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
