-- MySQL Script generated by MySQL Workbench
-- Sun Mar 17 14:12:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema antons_skafferi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema antons_skafferi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `antons_skafferi` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `antons_skafferi` ;

-- -----------------------------------------------------
-- Table `antons_skafferi`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`booking` (
  `booking_id` INT(11) NOT NULL AUTO_INCREMENT,
  `table_id` VARCHAR(45) NOT NULL,
  `people` INT(11) NOT NULL,
  `booking_from` TIME NOT NULL,
  `booking_to` TIME NOT NULL,
  `booking_date` DATE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `booking_description` VARCHAR(255) NULL DEFAULT NULL,
  `string_booking_from` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`booking_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`dinner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`dinner` (
  `dinner_id` VARCHAR(45) NOT NULL,
  `food_id` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`dinner_id`),
  UNIQUE INDEX `food_id_UNIQUE` (`food_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`drink` (
  `drink_id` VARCHAR(45) NOT NULL,
  `drink_name` VARCHAR(45) NOT NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`drink_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`event` (
  `event_id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `event_date` DATE NOT NULL,
  `event_title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`food` (
  `food_id` INT(11) NOT NULL AUTO_INCREMENT,
  `dish` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `ingrediens` VARCHAR(45) NULL DEFAULT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`food_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`images` (
  `image_id` INT(11) NOT NULL AUTO_INCREMENT,
  `srs` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`lunch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`lunch` (
  `lunch_id` VARCHAR(45) NOT NULL,
  `food_id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`lunch_id`),
  UNIQUE INDEX `food_id_UNIQUE` (`food_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`order` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `table_number` INT(11) NOT NULL,
  `item` VARCHAR(45) NOT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `amount` INT(11) NOT NULL,
  `active` TINYINT(4) NOT NULL,
  `date_time` TIMESTAMP NOT NULL,
  `prepared` TINYINT(4) NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`schedule` (
  `date` DATE NOT NULL,
  `staff_id` VARCHAR(12) NOT NULL,
  `start_hour` TIME NOT NULL,
  `end_hour` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`date`, `staff_id`, `start_hour`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`staff` (
  `staff_id` VARCHAR(12) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`dinnertable` (
  `table_id` INT(11) NOT NULL AUTO_INCREMENT,
  `seat` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`table_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO food (`food_id`,`dish`,`description`,`ingrediens`,`category`) VALUES (1,'Halstrad kammussla','Halstrad kammussla med jordärtskockskräm, syrlig fänkål, Kalixlöjrom och havskräftsoppa',NULL,'appetizer_menu');
INSERT INTO food (`food_id`,`dish`,`description`,`ingrediens`,`category`) VALUES (2,'Rostad rotselleri','Rostad rotselleri, rotsellerikräm, korngryn med brynt kantarell och mandel samt tryffel, hyvlad manchego och spansk körvel',NULL,'appetizer_menu');
INSERT INTO food (`food_id`,`dish`,`description`,`ingrediens`,`category`) VALUES (3,'Hjortytterfilé','Sotad hjortytterfilé med vinägersky, gratinerad blomkålspuré samt palsternacka med honung och citron',NULL,'main_menu');
INSERT INTO food (`food_id`,`dish`,`description`,`ingrediens`,`category`) VALUES (4,'Kalixgös','Ångad Kalixgös med dillsmörsås, konfiterad fänkål med timjan och lagerblad samt mandelpotatissufflé',NULL,'main_menu');
INSERT INTO food (`food_id`,`dish`,`description`,`ingrediens`,`category`) VALUES (5,'Lammytterfilé','Lammytterfilé med stuvad svamp, bakad spetskål, rostad potatis och vitlökssky',NULL,'main_menu');
INSERT INTO food (`food_id`,`dish`,`description`,`ingrediens`,`category`) VALUES (6,'Bakad choklad','Bakad choklad med hjortron, karamellglass och bovetepuffar',NULL,'dessert_menu');
INSERT INTO food (`food_id`,`dish`,`description`,`ingrediens`,`category`) VALUES (7,'Tiramisu','Klassisk italiensk efterrätt med krämig mascarpone',NULL,'dessert_menu');
INSERT INTO food (`food_id`,`dish`,`description`,`ingrediens`,`category`) VALUES (8,'Äppelpaj','Smulpaj med äpple, vaniljsås, havresmulor och smörkola',NULL,'dessert_menu');

INSERT INTO dinner (`dinner_id`,`food_id`,`price`) VALUES ('dinner1',1,165);
INSERT INTO dinner (`dinner_id`,`food_id`,`price`) VALUES ('dinner2',2,165);
INSERT INTO dinner (`dinner_id`,`food_id`,`price`) VALUES ('dinner3',3,260);
INSERT INTO dinner (`dinner_id`,`food_id`,`price`) VALUES ('dinner4',4,240);
INSERT INTO dinner (`dinner_id`,`food_id`,`price`) VALUES ('dinner5',5,240);
INSERT INTO dinner (`dinner_id`,`food_id`,`price`) VALUES ('dinner6',6,105);
INSERT INTO dinner (`dinner_id`,`food_id`,`price`) VALUES ('dinner7',7,105);
INSERT INTO dinner (`dinner_id`,`food_id`,`price`) VALUES ('dinner8',8,90);

INSERT INTO dinnertable (`table_id`,`seat`) VALUES (1,6);
INSERT INTO dinnertable (`table_id`,`seat`) VALUES (2,6);
INSERT INTO dinnertable (`table_id`,`seat`) VALUES (3,4);
INSERT INTO dinnertable (`table_id`,`seat`) VALUES (4,4);
INSERT INTO dinnertable (`table_id`,`seat`) VALUES (5,4);
INSERT INTO dinnertable (`table_id`,`seat`) VALUES (6,4);
INSERT INTO dinnertable (`table_id`,`seat`) VALUES (7,4);
INSERT INTO dinnertable (`table_id`,`seat`) VALUES (8,4);