-- MySQL Script generated by MySQL Workbench
-- Tue Mar  5 12:48:23 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema antons_skafferi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema antons_skafferi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `antons_skafferi` DEFAULT CHARACTER SET utf8 ;
USE `antons_skafferi` ;

-- -----------------------------------------------------
-- Table `antons_skafferi`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`booking` (
  `booking_id` INT(11) NOT NULL AUTO_INCREMENT,
  `table_id` VARCHAR(45) NOT NULL,
  `people` INT(11) NOT NULL,
  `from` TIME NOT NULL,
  `to` TIME NOT NULL,
  `date` DATE NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`booking_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`dinner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`dinner` (
  `dinner_id` VARCHAR(45) NOT NULL,
  `food_id` INT(11) NOT NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`dinner_id`),
  UNIQUE INDEX `food_id_UNIQUE` (`food_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`drink` (
  `drink_id` VARCHAR(45) NOT NULL,
  `drink_name` VARCHAR(45) NOT NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`drink_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`event` (
  `event_id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `event_title` VARCHAR(255) NOT NULL,
  `event_date` DATE NOT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`food` (
  `food_id` INT(11) NOT NULL AUTO_INCREMENT,
  `dish` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `ingrediens` VARCHAR(45) NULL DEFAULT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`food_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`images` (
  `image_id` INT(11) NOT NULL AUTO_INCREMENT,
  `srs` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`lunch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`lunch` (
  `lunch_id` VARCHAR(45) NOT NULL,
  `food_id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `price` INT(11) NOT NULL,
  PRIMARY KEY (`lunch_id`),
  UNIQUE INDEX `food_id_UNIQUE` (`food_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`order1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`order1` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `table_number` INT(11) NOT NULL,
  `item` VARCHAR(45) NOT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `amount` INT(11) NOT NULL,
  `active` TINYINT(4) NOT NULL,
  `date_time` TIMESTAMP NOT NULL,
  `prepared` TINYINT(4) NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`schedule` (
  `date` DATE NOT NULL,
  `staff_id` VARCHAR(12) NOT NULL,
  `start_hour` TIME NOT NULL,
  `end_hour` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`date`, `staff_id`, `start_hour`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`staff` (
  `staff_id` VARCHAR(12) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `antons_skafferi`.`table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `antons_skafferi`.`table` (
  `table_id` INT(11) NOT NULL AUTO_INCREMENT,
  `seat` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`table_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
